### ISSUE TITLE
path substitutions in diagram block macro doesn't work

### ISSUE THREAD

**Issue by felux** [asciidoctor/asciidoctor-diagram#133]
Hello,
in Asciidoctor it is possible to split a document into several files with the include directive.
The following code snippet illustrates what I mean:

``` Asciidoc
:includedir: include

...

include::{includedir}/test.adoc[]
```

Now I wanted to apply this approach to some plantuml diagrams as follows:

``` AsciiDoc
:imagesdir: ./images
:umldir: {imagedir}/uml

= Test document

plantuml::{umldir}/classTest.plantuml[classTest, svg]
```
Unfortunately, this produces the following error in the Windows PowerShell:

``` PowerShell
PS D:\temp\test> asciidoctor.bat -r asciidoctor-diagram .\test.adoc --trace
asciidoctor-diagram: ERROR: Failed to generate image: No such file or directory @ rb_sysopen - D:/temp/test/{umldir}/classTest.plantuml
C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-diagram-1.5.2/lib/asciidoctor-diagram/extensions.rb:459:in `read
lines': asciidoctor: FAILED: D:/temp/test/test.adoc: Failed to load AsciiDoc document - No such file or directory @ rb_s
ysopen - D:/temp/test/{umldir}/classTest.plantuml (Errno::ENOENT)
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-diagram-1.5.2/lib/asciidoctor-diagram/extensions.rb:459:in `read_code'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-diagram-1.5.2/lib/asciidoctor-diagram/extensions.rb:454:in `code'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-diagram-1.5.2/lib/asciidoctor-diagram/extensions.rb:124:in `rescue in process'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-diagram-1.5.2/lib/asciidoctor-diagram/extensions.rb:105:in `process'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:589:in `[]'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:589:in `next_block'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:315:in `next_section'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/parser.rb:67:in `parse'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/document.rb:472:in `parse'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1347:in `load'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor.rb:1465:in `convert'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:95:in `block in invoke!'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `each'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/lib/asciidoctor/cli/invoker.rb:87:in `invoke!'
        from C:/Ruby/Ruby23-x64/lib/ruby/gems/2.3.0/gems/asciidoctor-1.5.5/bin/asciidoctor:14:in `<top (required)>'
        from C:/Ruby/Ruby23-x64/bin/asciidoctor:22:in `load'
        from C:/Ruby/Ruby23-x64/bin/asciidoctor:22:in `<main>'
```

It seems that the `{umldir}` is not substituted with `include/uml`. Is it possible to implement this path substitution in the diagram block macro too?

Thanks in advance.

**Comment by pepijnve** [comment]
This is easy enough to do; just want to check with @mojavelinux how this should work before making any changes.

@mojavelinux whose responsibility is it to perform this substitution? asciidoctor itself or the extension handling the target value? What about other attribute values? Should subs be applied to those as well?

**Comment by mojavelinux** [comment]
Performing substitution on the macro target is up to the extension. That way, the extension is aware of the whole context and can do extra magic if necessary. (In the future, we could consider making automatic substitutions a setting in the extension DSL).

Here's the line I use for the media macros (like image, video, etc):

```ruby
target = block.sub_attributes(target, :attribute_missing => 'drop-line')
```

**Comment by mojavelinux** [comment]
If you'd like an enhancement to the DSL, feel free to propose in core.

**Comment by pepijnve** [comment]
I don't think there's a need for changes in the DSL. Just wanted to check what the division of responsibilities is supposed to be before making changes.
