### ISSUE TITLE
asciidoctor-diagram-1.5.14 is incompatible with asciidoctor-2.0.0.rc.1

### ISSUE THREAD

**Issue by alexeikh** [asciidoctor/asciidoctor-diagram#217]
## Summary
asciidoctor-diagram seems to be incompatible with asciidoctor 2.x, despite commit https://github.com/asciidoctor/asciidoctor-diagram/commit/38e9301cf62f61947b6c97132d1e1229248b4f2d .

## Steps to reproduce

1. Install the following gems:
```
asciidoctor (2.0.0.rc.1, 1.5.8)
asciidoctor-diagram (1.5.14)
```

2. Try to use asciidoctor-diagram:
```
touch empty.adoc
asciidoctor --trace -r asciidoctor-diagram empty.adoc
```

Observed output:
```
Traceback (most recent call last):
        14: from /usr/local/bin/asciidoctor:23:in `<main>'
        13: from /usr/local/bin/asciidoctor:23:in `load'
        12: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/bin/asciidoctor:13:in `<top (required)>'
        11: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/bin/asciidoctor:13:in `new'
        10: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/cli/invoker.rb:24:in `initialize'
         9: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/cli/options.rb:38:in `parse!'
         8: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/cli/options.rb:274:in `parse!'
         7: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/cli/options.rb:274:in `each'
         6: from /var/lib/gems/2.5.0/gems/asciidoctor-2.0.0.rc.1/lib/asciidoctor/cli/options.rb:276:in `block in parse!'
         5: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:39:in `require'
         4: from /usr/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
         3: from /usr/lib/ruby/2.5.0/rubygems.rb:217:in `try_activate'
         2: from /usr/lib/ruby/2.5.0/rubygems.rb:224:in `rescue in try_activate'
         1: from /usr/lib/ruby/2.5.0/rubygems/specification.rb:1438:in `activate'
/usr/lib/ruby/2.5.0/rubygems/specification.rb:2327:in `raise_if_conflicts': Unable to activate asciidoctor-diagram-1.5.14, because asciidoctor-2.0.0.rc.1 conflicts with asciidoctor (~> 1.5.0) (Gem::ConflictError)
```
Expected: No error.

3. Try to uninstall asciidoctor-1.5.8:
```
gem uninstall asciidoctor --version 1.5.8
```

Observed output:
```
asciidoctor-diagram-1.5.14 depends on asciidoctor (~> 1.5.0)
If you remove this gem, these dependencies will not be met.
```

Expected: asciidoctor-1.5.8 is removed, asciidoctor-2.0.0.rc.1 satisfies asciidoctor-diagram's dependency on asciidoctor.

4. Look at https://github.com/asciidoctor/asciidoctor-diagram/blob/master/asciidoctor-diagram.gemspec .

Observed:
```
s.add_runtime_dependency 'asciidoctor', ENV['ASCIIDOCTOR_VERSION'] || '~> 1.5.0'
```
Expected: asciidoctor 2.x should also be treated as a valid dependency.

**Comment by pepijnve** [comment]
Thanks for spotting this. Oversight on my part. I'll get this fixed asap so that there are no issues by the time Asciidoctor 2.0.0 is released.

**Comment by mojavelinux** [comment]
I've been trying hard to make 2.0.0 backwards compatible. If there's
something I need to adjust to ensure that, I'd be happy to do so.

**Comment by mojavelinux** [comment]
Ah, I see now. :wink:

**Comment by pepijnve** [comment]
The asciidoctor version constraint in the Gemspec has been updated to `'>= 1.5.0', '< 3.x'` in diagram 1.5.15.

**Comment by alexeikh** [comment]
I have upgraded to the release 1.5.15 and confirming that I can no longer reproduce the issue.
