### ISSUE TITLE
cannot load such file asciidoctor/logging

### ISSUE THREAD

**Issue by amejiarosario** [asciidoctor/asciidoctor-diagram#228]
I'm running
```
asciidoctor --trace -r asciidoctor-diagram book.adoc
```
and I'm getting
<details>
  <summary>
<code>
.../asciidoctor-diagram/extensions.rb:3:in `require': cannot load such file -- asciidoctor/logging (LoadError)
</code>

</summary>

```
/Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram/extensions.rb:3:in `require': cannot load such file -- asciidoctor/logging (LoadError)
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram/extensions.rb:3:in `<top (required)>'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram/a2s/extension.rb:1:in `require_relative'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram/a2s/extension.rb:1:in `<top (required)>'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram/a2s.rb:2:in `require_relative'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram/a2s.rb:2:in `<top (required)>'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram.rb:1:in `require_relative'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-diagram-1.5.18/lib/asciidoctor-diagram.rb:1:in `<top (required)>'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/options.rb:230:in `require'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/options.rb:230:in `block in parse!'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/options.rb:228:in `each'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/options.rb:228:in `parse!'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/options.rb:33:in `parse!'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-1.5.6.1/lib/asciidoctor/cli/invoker.rb:22:in `initialize'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-1.5.6.1/bin/asciidoctor:12:in `new'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/gems/asciidoctor-1.5.6.1/bin/asciidoctor:12:in `<top (required)>'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/bin/asciidoctor:23:in `load'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/bin/asciidoctor:23:in `<main>'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `eval'
        from /Users/admejiar/.rvm/gems/ruby-2.6.3/bin/ruby_executable_hooks:24:in `<main>'
```  
</details>

How do I fix this?

Versions:
```
$ asciidoctor --version
Asciidoctor 1.5.6.1 [http://asciidoctor.org]
Runtime Environment (ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:- ex:UTF-8)

$ ruby --version                                                                                                                                             
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]

asciidoctor-diagram (1.5.18)
```

**Comment by mojavelinux** [comment]
> Asciidoctor 1.5.6.1

There's your problem. You should really be on Asciidoctor 2.0.10 by now.

**Comment by mojavelinux** [comment]
@pepijnve If you'd like to retain backwards compatibility with older releases of 1.5.x, you can steal this code:

* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/asciidoctor_ext/logging_shim.rb
* https://github.com/asciidoctor/asciidoctor-pdf/blob/master/lib/asciidoctor-pdf/converter.rb#L31-L35

**Comment by amejiarosario** [comment]
Ah, that's for the info. Upgrading to 2.x fixed it. Thanks!

**Comment by pepijnve** [comment]
> @pepijnve If you'd like to retain backwards compatibility with older releases of 1.5.x, you can steal this code:

It’s probably better to make the asciidoctor dependency requirement stricter. Recent 1.5 or 2.x.
