### ISSUE TITLE
Error generating PlantUml graph

### ISSUE THREAD

**Issue by jul13nc** [asciidoctor/asciidoctor-diagram#242]
I'm using asciidoctor to generate plantuml graph within my documentation.
When I tried to generate the below graph (which seems valid according to the plantuml server

["plantuml"]
--------------------------
@startuml
package SomPackage {
    boundary boundary
    card card
    cloud cloud
}
@enduml
--------------------------

 the conversion reported the following error

Exception java.lang.IllegalStateException: Cannot find color #000005
net.sourceforge.plantuml.cucadiagram.UnparsableGraphvizException: java.lang.IllegalStateException: Cannot find color #000005
        at net.sourceforge.plantuml.svek.GeneralImageBuilder.buildImage(GeneralImageBuilder.java:215)
        at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFileInternal(CucaDiagramFileMakerSvek.java:100)
        at net.sourceforge.plantuml.svek.CucaDiagramFileMakerSvek.createFile(CucaDiagramFileMakerSvek.java:66)
        at net.sourceforge.plantuml.cucadiagram.CucaDiagram.exportDiagramInternal(CucaDiagram.java:374)
        at net.sourceforge.plantuml.UmlDiagram.exportDiagramNow(UmlDiagram.java:197)
        at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)

Is there something I have missed ?
Or the plantuml not fully supported ?

**Comment by jul13nc** [comment]
I answer to myself, maybe this will help someone.

The problem was with the configuration of asciidoctor-diagram, I didn't set the graphvizdot attribute, so my local instance of graphviz was not found.

Setting it correctly solved my problem

To check if your install is ok, try generating the following graph
@startuml
testdot
@enduml
