### ISSUE TITLE
Generating HTML or PDF output of a document with an incorrect mermaid diagram causes hanging

### ISSUE THREAD

**Issue by roland-hediger** [asciidoctor/asciidoctor-diagram#257]
Hi there asciidoctor-pdf devs,

I am currently using asciidoctor pdf for my dissertation. Its working out great so far.
I am using the following code in my documenté
```
.Device Registration Use Case
[mermaid, diagram-registration, svg]
....
S[Start Mobile Application] 
--> R[User clicks Registration] 
....
```
I left out some irrelevant stuff.
Nevertheless when running my document generation using the following command
```
 asciidoctor-pdf --verbose -a pdf-theme=resources/basic-theme.yml -r asciidoctor-mathematical -r asciidoctor-bibtex -r asciidoctor-diagram  index.adoc
```
I am running Mac OSX Catalina, and I used `yarn global install  mermaid.cli` to install mermaid. 

I am running into a never ending loop . i.e the document never finishes generating.
I tried to see with the verbose flag and the trace flag if I could get more information. However this was not the case.

I also tried only using the asciidoctor diagram generator.
Interestingly enough all my plantuml diagrams work, and the problem occurs as soon as I want to use mermaid.

Can someone please tell me what I am missing here? or how to get a better log of what is happening so I can give you more useful information? thanks,

**Comment by pepijnve** [comment]
@mojavelinux that was my initial thought when reading 'a never ending loop' as well, but that issue is only applicable to Java based generators on Windows. This is mermaid (JS) on macOS, so probably something different.

**Comment by mojavelinux** [comment]
Ah, thanks for clarifying.

**Comment by pepijnve** [comment]
@roland-hediger looks like a mermaid issue. If I try to run your diagram through `mmdc` manually I get the following output

```
pepijn@Cerris asciidoctor-diagram % mmdc -o test.svg -i test.mmd 
(node:18311) UnhandledPromiseRejectionWarning: Error: Evaluation failed: Error: Parse error on line 1:
S[Start Mobile Appli
^
Expecting 'NEWLINE', 'SPACE', 'GRAPH', got 'ALPHA'
    at Yt.parseError (file:///Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:486512)
    at Yt.parse (file:///Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:487678)
    at Object.e.getClasses (file:///Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:749437)
    at Object.render (file:///Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:1:759998)
    at s (file:///Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:8:233)
    at Object.init (file:///Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/mermaid.min.js:8:318)
    at __puppeteer_evaluation_script__:17:20
    at ExecutionContext._evaluateInternal (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/ExecutionContext.js:122:13)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async ExecutionContext.evaluate (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/ExecutionContext.js:48:12)
    at async ElementHandle.evaluate (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/JSHandle.js:55:12)
    at async ElementHandle.$eval (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/JSHandle.js:478:20)
  -- ASYNC --
    at ExecutionContext.<anonymous> (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
    at ElementHandle.evaluate (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/JSHandle.js:55:42)
    at ElementHandle.<anonymous> (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/helper.js:112:23)
    at ElementHandle.$eval (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/JSHandle.js:478:40)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at ElementHandle.<anonymous> (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
    at DOMWorld.$eval (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/DOMWorld.js:156:21)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
  -- ASYNC --
    at Frame.<anonymous> (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/helper.js:111:15)
    at Page.$eval (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/Page.js:347:29)
    at Page.<anonymous> (/Users/pepijn/.config/yarn/global/node_modules/puppeteer/lib/helper.js:112:23)
    at /Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:83:14
    at Generator.next (<anonymous>)
    at step (/Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:4:191)
    at /Users/pepijn/.config/yarn/global/node_modules/mermaid.cli/index.bundle.js:4:361
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:18311) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:18311) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

That last statement explains why the process never exits. Running `node --unhandled-rejections=strict /usr/local/bin/mmdc -o test.svg -i test.mmd` instead does cause the process to quit as expected. I'm not 100% sure how we should deal with this yet.

**Comment by pepijnve** [comment]
I've logged https://github.com/mermaidjs/mermaid.cli/issues/77 to track the issue in the mermaid project. I think in the meantime invoking node directly is probably the only thing we can do in the context of asciidoctor-diagram.

**Comment by roland-hediger** [comment]
Thanks @pepijnve , This means that my latest test results correlate with your error -- even in the case of a syntactically correct diagram (which can be generated with mmdc on its own - asciidoctor diagram still hangs.
