### ISSUE TITLE
plantuml.jar lack js files for math diagram

### ISSUE THREAD

**Issue by chunlinyao** [asciidoctor/asciidoctor-diagram#259]
The plantuml.jar included in asciidoctor-diagram not include these two js files:
```
net/sourceforge/plantuml/math/ASCIIMathTeXImg.js
net/sourceforge/plantuml/math/AsciiMathParser.js
```
When I include this math diagram in adoc, It thrown NullPointerException.

```
[plantuml,jjj,svg]
....
@startmath
f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
@endmath
....
```

This is the error log:
```
java.lang.NullPointerException
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at net.sourceforge.plantuml.math.AsciiMath.<clinit>(AsciiMath.java:61)
	at net.sourceforge.plantuml.math.ScientificEquationSafe.fromAsciiMath(ScientificEquationSafe.java:67)
	at net.sourceforge.plantuml.math.PSystemMath.exportDiagramNow(PSystemMath.java:63)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)
	at org.asciidoctor.diagram.plantuml.PlantUML.generate(PlantUML.java:126)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:40)
	at org.asciidoctor.diagram.AbstractCommandServer.processRequests(AbstractCommandServer.java:47)
	at org.asciidoctor.diagram.StdInOutCommandServer.processRequests(StdInOutCommandServer.java:20)
	at org.asciidoctor.diagram.StdInOutCommandServer.main(StdInOutCommandServer.java:12)
java.lang.NullPointerException
	at java.util.Objects.requireNonNull(Objects.java:203)
	at jdk.nashorn.internal.runtime.Source$RawData.<init>(Source.java:169)
	at jdk.nashorn.internal.runtime.Source$RawData.<init>(Source.java:158)
	at jdk.nashorn.internal.runtime.Source.sourceFor(Source.java:429)
	at jdk.nashorn.internal.runtime.Source.sourceFor(Source.java:440)
	at jdk.nashorn.api.scripting.NashornScriptEngine.makeSource(NashornScriptEngine.java:226)
	at jdk.nashorn.api.scripting.NashornScriptEngine.eval(NashornScriptEngine.java:155)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:264)
	at net.sourceforge.plantuml.math.AsciiMath.<init>(AsciiMath.java:78)
	at net.sourceforge.plantuml.math.ScientificEquationSafe.fromAsciiMath(ScientificEquationSafe.java:67)
	at net.sourceforge.plantuml.math.PSystemMath.exportDiagramNow(PSystemMath.java:63)
	at net.sourceforge.plantuml.AbstractPSystem.exportDiagram(AbstractPSystem.java:130)
	at org.asciidoctor.diagram.plantuml.PlantUML.generate(PlantUML.java:126)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:40)
	at org.asciidoctor.diagram.AbstractCommandServer.processRequests(AbstractCommandServer.java:47)
	at org.asciidoctor.diagram.StdInOutCommandServer.processRequests(StdInOutCommandServer.java:20)
	at org.asciidoctor.diagram.StdInOutCommandServer.main(StdInOutCommandServer.java:12)
formula=f(t)=(a_0)/2 + sum_(n=1)^ooa_ncos((npit)/L)+sum_(n=1)^oo b_n\ sin((npit)/L)
asciidoctor: ERROR: src/01_introduction_and_goals.adoc: line 189: Failed to generate image: PlantUML image generation failed:
```
This diagram can generated image correctly by my plantuml server. Which is started by `docker run -d -p 8080:8080 plantuml/plantuml-server:jetty`

Replace the plantuml.jar with the offical version fix the problem.

**Comment by pepijnve** [comment]
The files you mentioned are LGPL licensed and as a consequence they cannot be included in this extension. The bundled PlantUML jar is the ASL licensed one. I do not wish to relicense this extension under LGPL so you're request is simply not possible at the moment.

**Comment by Mogztter** [comment]
Disclaimer: I'm not a license expert but here's what https://tldrlegal.com/license/gnu-lesser-general-public-license-v3-(lgpl-3) says:

> This license is mainly applied to libraries. You may copy, distribute and modify the software provided that modifications are described and licensed for free under LGPL. Derivatives works (including modifications or anything statically linked to the library) can only be redistributed under LGPL, **but applications that use the library don't have to be.**


@pepijnve In this case, Asciidoctor Diagram is an application that uses the library no?
