### ISSUE TITLE
Running asciidoctor doesn't fail on ditaa error

### ISSUE THREAD

**Issue by knl** [asciidoctor/asciidoctor-diagram#273]
## Description of the problem

If I use the following, faulty adoc, saved as `index.adoc`:

```
= Bug reproduction
ifdef::env-github,env-browser[:outfilesuffix:.adoc]

lorem ipsum

== Introduction

// edit in http://asciiflow.com (make sure there are spaces in between lines)
[ditaa]
....
This should cause a bug.

// TODO:
// - don't make bugs
// - oops I wrote a comment here

    +--------+   +-------+    +-------+
    |        | --+ ditaa +--> |       |
    |  Text  |   +-------+    |diagram|
    |Document|   |!magic!|    |       |
    |     {d}|   |       |    |       |
    +---+----+   +-------+    +-------+
        :                         ^
        |       Lots of work      |
        +-------------------------+
....
```

with the following command:

```
$ asciidoctor -r asciidoctor-diagram index.adoc
Umbiguous input at position (3, 5):
java.lang.RuntimeException: Cannot follow cell (3, 5): cannot determine cell type
	at org.stathissideris.ascii2image.text.TextGrid.followCell(TextGrid.java:995)
	at org.stathissideris.ascii2image.text.TextGrid.followCell(TextGrid.java:982)
	at org.stathissideris.ascii2image.text.CellSet.getTypeAccordingToTraceMethod(CellSet.java:177)
	at org.stathissideris.ascii2image.text.CellSet.getType(CellSet.java:129)
	at org.stathissideris.ascii2image.graphics.Diagram.<init>(Diagram.java:215)
	at org.stathissideris.ascii2image.core.CommandLineConverter.convertToImage(CommandLineConverter.java:144)
	at org.stathissideris.ascii2image.core.CommandLineConverter.doConvert(CommandLineConverter.java:110)
	at org.stathissideris.ascii2image.core.CommandLineConverter.convert(CommandLineConverter.java:97)
	at org.asciidoctor.diagram.ditaa.Ditaa.generate(Ditaa.java:68)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:40)
	at org.asciidoctor.diagram.AbstractCommandServer.processRequests(AbstractCommandServer.java:47)
	at org.asciidoctor.diagram.StdInOutCommandServer.processRequests(StdInOutCommandServer.java:20)
	at org.asciidoctor.diagram.StdInOutCommandServer.main(StdInOutCommandServer.java:12)
asciidoctor: ERROR: index.adoc: line 10: Failed to generate image: Invalid PNG signature

$ echo $?
0
```

I would expect that the command fails, instead of silently succeeding.

## Other information

```
$ asciidoctor -v
Asciidoctor 2.0.10 [https://asciidoctor.org]
Runtime Environment (ruby 2.6.5p114 (2019-10-01) [x86_64-darwin18]) (lc:UTF-8 fs:UTF-8 in:UTF-8 ex:UTF-8)

$ uname -a
Darwin yggdrasil.local 18.7.0 Darwin Kernel Version 18.7.0: Thu Jan 23 06:52:12 PST 2020; root:xnu-4903.278.25~1/RELEASE_X86_64 x86_64
```

**Comment by pepijnve** [comment]
@knl there have been requests for both log-and-continue and abort. You can control this using the `diagram-on-error` document attribute. The valid options are `log` and `abort`. In case of `abort` asciidoc processing will stop at the first error.

**Comment by knl** [comment]
Thanks @pepijnve, I was not aware of this attribute. I can confirm that with this invocation, it works:

```
$ asciidoctor -r asciidoctor-diagram -a diagram-on-error=abort index.adoc
Umbiguous input at position (3, 5):
java.lang.RuntimeException: Cannot follow cell (3, 5): cannot determine cell type
	at org.stathissideris.ascii2image.text.TextGrid.followCell(TextGrid.java:995)
	at org.stathissideris.ascii2image.text.TextGrid.followCell(TextGrid.java:982)
	at org.stathissideris.ascii2image.text.CellSet.getTypeAccordingToTraceMethod(CellSet.java:177)
	at org.stathissideris.ascii2image.text.CellSet.getType(CellSet.java:129)
	at org.stathissideris.ascii2image.graphics.Diagram.<init>(Diagram.java:215)
	at org.stathissideris.ascii2image.core.CommandLineConverter.convertToImage(CommandLineConverter.java:144)
	at org.stathissideris.ascii2image.core.CommandLineConverter.doConvert(CommandLineConverter.java:110)
	at org.stathissideris.ascii2image.core.CommandLineConverter.convert(CommandLineConverter.java:97)
	at org.asciidoctor.diagram.ditaa.Ditaa.generate(Ditaa.java:68)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:40)
	at org.asciidoctor.diagram.AbstractCommandServer.processRequests(AbstractCommandServer.java:47)
	at org.asciidoctor.diagram.StdInOutCommandServer.processRequests(StdInOutCommandServer.java:20)
	at org.asciidoctor.diagram.StdInOutCommandServer.main(StdInOutCommandServer.java:12)
asciidoctor: FAILED: /private/tmp/repro/index.adoc: Failed to load AsciiDoc document - Invalid PNG signature (RuntimeError)
  Use --trace for backtrace

$ echo $?
1
```

However, strangely, with the following one, it fails to fail:

```
$ asciidoctor -r asciidoctor-diagram -a diagram-on-error=abort -a ditaa-format=svg -R . -D /tmp/foo/bar index.adoc
Umbiguous input at position (3, 5):
java.lang.RuntimeException: Cannot follow cell (3, 5): cannot determine cell type
	at org.stathissideris.ascii2image.text.TextGrid.followCell(TextGrid.java:995)
	at org.stathissideris.ascii2image.text.TextGrid.followCell(TextGrid.java:982)
	at org.stathissideris.ascii2image.text.CellSet.getTypeAccordingToTraceMethod(CellSet.java:177)
	at org.stathissideris.ascii2image.text.CellSet.getType(CellSet.java:129)
	at org.stathissideris.ascii2image.graphics.Diagram.<init>(Diagram.java:215)
	at org.stathissideris.ascii2image.core.CommandLineConverter.convertToImage(CommandLineConverter.java:144)
	at org.stathissideris.ascii2image.core.CommandLineConverter.doConvert(CommandLineConverter.java:110)
	at org.stathissideris.ascii2image.core.CommandLineConverter.convert(CommandLineConverter.java:97)
	at org.asciidoctor.diagram.ditaa.Ditaa.generate(Ditaa.java:68)
	at org.asciidoctor.diagram.CommandProcessor.processRequest(CommandProcessor.java:40)
	at org.asciidoctor.diagram.AbstractCommandServer.processRequests(AbstractCommandServer.java:47)
	at org.asciidoctor.diagram.StdInOutCommandServer.processRequests(StdInOutCommandServer.java:20)
	at org.asciidoctor.diagram.StdInOutCommandServer.main(StdInOutCommandServer.java:12)

$ echo $?
0
```

The difference is in `-a ditaa-format=svg`. If I run it with explicit `-a ditaa-format=png`, the call properly fails on error.
